openapi: 3.0.3
info:
  title: 3040 API
  description: |
    3040 서비스의 API 명세서입니다.
  version: 1.0.0
  contact:
    name: developer - xi600
    email: excited600@gmail.com

servers:
  - url: http://localhost:8080
    description: 로컬 서버

tags:
  - name: Gatherings
    description: 모임
  - name: Users
    description: 사용자

paths:
  # Gatherings
  /gatherings:
    $ref: './paths/gatherings.yml#/~1gatherings'
  /series:
    $ref: './paths/gatherings.yml#/~1series'
  /gatherings/{gatheringUuid}/join:
    $ref: './paths/gatherings.yml#/~1gatherings~1{gatheringUuid}~1join'

  # Payments
  /payments/{paymentId}/prepare:
    $ref: './paths/payments.yml#/~1payments~1{paymentId}~1prepare'
  /payments/{paymentId}/verify:
    $ref: './paths/payments.yml#/~1payments~1{paymentId}~1verify'
  /payments/webhook:
    $ref: './paths/payments.yml#/~1payments~1webhook'

components:
  schemas:
    # Gatherings
    OpenGatheringRequest:
      $ref: './components/schemas/gathering/openGathering/openGatheringRequest.yml#/OpenGatheringRequest'
    OpenGatheringResponse:
      $ref: './components/schemas/gathering/openGathering/openGatheringResponse.yml#/OpenGatheringResponse'
    ScheduleSeriesRequest:
      $ref: './components/schemas/gathering/scheduleSeries/scheduleSeriesRequest.yml#/ScheduleSeriesRequest'
    WeeklyScheduleSeriesRequest:
      $ref: './components/schemas/gathering/scheduleSeries/scheduleSeriesRequest.yml#/WeeklyScheduleSeriesRequest'
    DateScheduleSeriesRequest:
      $ref: './components/schemas/gathering/scheduleSeries/scheduleSeriesRequest.yml#/DateScheduleSeriesRequest'
    Gathering:
      $ref: './components/schemas/gathering/gathering.yml#/Gathering'
    ScrollFilteredGatheringsResponse:
      $ref: './components/schemas/gathering/scrollFilteredGatherings/scrollFilteredGatheringsResponse.yml#/ScrollFilteredGatheringsResponse'
    JoinGatheringRequest:
      $ref: './components/schemas/gathering/joinGathering/joinGatheringRequest.yml#/JoinGatheringRequest'

    # Payments
    PreparePaymentRequest:
      $ref: './components/schemas/payment/preparePayment/preparePaymentRequest.yml#/PreparePaymentRequest'
    PreparePaymentResponse:
      $ref: './components/schemas/payment/preparePayment/preparePaymentResponse.yml#/PreparePaymentResponse'
    PaymentWebhook:
      $ref: './components/schemas/payment/webhook/paymentWebhook.yml#/PaymentWebhook'

#    # Users
#    SignUpRequest:
#      $ref: './components/schemas/users.yml#/SignUpRequest'
#    SignUpResponse:
#      $ref: './components/schemas/users.yml#/SignUpResponse'