openapi: 3.0.3
info:
  title: 3040 API
  description: |
    3040 서비스의 API 명세서입니다.
  version: 1.0.0
  contact:
    name: developer - xi600
    email: excited600@gmail.com

servers:
  - url: http://localhost:8080
    description: 로컬 서버

tags:
  - name: Gatherings
    description: 모임
  - name: Users
    description: 사용자

paths:
  # Gatherings
  /gatherings:
    $ref: './paths/gatherings.yml#/~1gatherings'
  /gatherings/schedules:
    $ref: './paths/gatherings.yml#/~1gatherings~1schedules'

components:
  schemas:
    # Gatherings
    #    GetGatheringsResponse:
    #      $ref: './components/schemas/gatherings.yml#/GetGatheringsResponse'
    OpenGatheringRequest:
      $ref: './components/schemas/gatherings.yml#/OpenGatheringRequest'
    OpenGatheringResponse:
      $ref: './components/schemas/gatherings.yml#/OpenGatheringResponse'
    ScheduleGatheringsRequest:
      $ref: './components/schemas/gatherings.yml#/ScheduleGatheringsRequest'
    WeeklyScheduleGatheringsRequest:
      $ref: './components/schemas/gatherings.yml#/WeeklyScheduleGatheringsRequest'
    DateScheduleGatheringsRequest:
      $ref: './components/schemas/gatherings.yml#/DateScheduleGatheringsRequest'

#    # Users
#    SignUpRequest:
#      $ref: './components/schemas/users.yml#/SignUpRequest'
#    SignUpResponse:
#      $ref: './components/schemas/users.yml#/SignUpResponse'