version: '3.8'
services:
  postgres-test:
    image: postgres:16
    container_name: 3040-postgres-test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: 3040
    ports:
      - "15432:5432"