ALTER TABLE gatherings ADD COLUMN is_free BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE gatherings SET is_free = TRUE WHERE fee = 0;
ALTER TABLE gatherings ALTER COLUMN is_free DROP DEFAULT;

ALTER TABLE gatherings ALTER COLUMN fee DROP NOT NULL;
