spring:
  profiles:
    active: local
  application:
    name: 30damm
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

portone:
  base-url: https://api.portone.io

springdoc:
  api-docs:
    enabled: false
