spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/30damm
    username: root
    password: beyondeyesight
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: beyondeyesight

jwt:
  secret: dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHRva2VuIGdlbmVyYXRpb24gMzBkYW1t
  access-token-expiry: 86400000
  refresh-token-expiry: 31536000000

portone:
  api-secret: Na5vnSd3bSdBtded0DGBWxQbVD8u6oSMHzvvhr7ohSTNm8PyLvSFn4qQlYA2Fq9cVRnBgrf4N6JHGcs7
  store-id: store-c47dce95-6209-4f04-87f1-78914a40214a
  channel-key: channel-key-8704e9d0-feb4-4cdd-96a6-34e8238a726f
