spring:
  application:
    name: 3040
  datasource:
    url: jdbc:postgresql://localhost:5432/3040
    username: root
    password: beyondeyesight
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
      password: beyondeyesight

jwt:
  secret: dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHRva2VuIGdlbmVyYXRpb24gMzA0MA==
  access-token-expiry: 3600000
  refresh-token-expiry: 604800000

portone:
  api-secret: Na5vnSd3bSdBtded0DGBWxQbVD8u6oSMHzvvhr7ohSTNm8PyLvSFn4qQlYA2Fq9cVRnBgrf4N6JHGcs7
  store-id: store-c47dce95-6209-4f04-87f1-78914a40214a
  base-url: https://api.portone.io
  channel-key: channel-key-8704e9d0-feb4-4cdd-96a6-34e8238a726f

springdoc:
  api-docs:
    enabled: false
