spring:
  application:
    name: 3040
  datasource:
    url: jdbc:postgresql://localhost:5432/3040
    username: root
    password: beyondeyesight
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
      password: beyondeyesight

portone:
  api-secret: Na5vnSd3bSdBtded0DGBWxQbVD8u6oSMHzvvhr7ohSTNm8PyLvSFn4qQlYA2Fq9cVRnBgrf4N6JHGcs7
  base-url: https://api.portone.io

springdoc:
  api-docs:
    enabled: false
