openapi: 3.0.3
info:
  contact:
    email: excited600@gmail.com
    name: developer - xi600
  description: |
    3040 서비스의 API 명세서입니다.
  title: 3040 API
  version: 1.0.0
servers:
- description: 로컬 서버
  url: http://localhost:8080
tags:
- description: 모임
  name: Gatherings
- description: 사용자
  name: Users
paths:
  /gatherings:
    post:
      operationId: openGathering
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenGatheringRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenGatheringResponse"
          description: Gathering open successfully
      summary: Open a new gathering
      tags:
      - Gatherings
  /series:
    post:
      operationId: scheduleSeries
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleSeriesRequest"
        required: true
      responses:
        "201":
          description: Gatherings scheduled successfully
      summary: Schedule gatherings based on host setting
      tags:
      - Gatherings
components:
  schemas:
    OpenGatheringRequest:
      example:
        maxMaleCount: 1
        approveType: FIRST_IN
        subCategory: HOME_PARTY
        fee: 7
        maxCapacity: 6
        title: title
        discountEnabled: true
        maxFemaleCount: 5
        duration: 9.301444
        offline: true
        genderRatioEnabled: true
        startDateTime: 2000-01-23T04:56:07.000+00:00
        hostUuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        maxAge: 2
        minAge: 5
        imageUrl: imageUrl
        minCapacity: 0
        place: place
        category: PARTY
        introduction: introduction
      properties:
        hostUuid:
          description: UUID of the host. tmp property
          format: uuid
          type: string
        approveType:
          $ref: "#/components/schemas/Gathering_ApproveType"
        minCapacity:
          description: Minimum capacity of the gathering
          type: integer
        maxCapacity:
          description: Maximum capacity of the gathering
          type: integer
        maxMaleCount:
          description: Maximum number of male guests
          type: integer
        maxFemaleCount:
          description: Maximum number of female guests
          type: integer
        genderRatioEnabled:
          description: If host can set gender ratio for the gathering
          type: boolean
        minAge:
          description: Minimum age of guests
          type: integer
        maxAge:
          description: Maximum age of guests
          type: integer
        fee:
          description: Fee to join the gathering
          type: integer
        discountEnabled:
          description: If host can set discount strategy for the gathering
          type: boolean
        offline:
          description: If the gathering is offline
          type: boolean
        place:
          description: Place where the gathering will be held
          type: string
        category:
          $ref: "#/components/schemas/Gathering_Category"
        subCategory:
          $ref: "#/components/schemas/Gathering_SubCategory"
        imageUrl:
          description: URL of the gathering image
          type: string
        title:
          description: Title of the gathering
          type: string
        introduction:
          description: Introduction of the gathering
          type: string
        startDateTime:
          description: Start date and time of the gathering
          format: date-time
          type: string
        duration:
          description: Duration of the gathering in hours (can contain decimals)
          format: float
          type: number
      required:
      - approveType
      - category
      - discountEnabled
      - fee
      - genderRatioEnabled
      - hostUuid
      - imageUrl
      - introduction
      - maxAge
      - maxCapacity
      - minAge
      - minCapacity
      - offline
      - place
      - startDateTime
      - subCategory
      - title
      type: object
    OpenGatheringResponse:
      example:
        maxMaleCount: 5
        approveType: FIRST_IN
        subCategory: HOME_PARTY
        clickCount: 3
        fee: 9
        maxCapacity: 6
        totalGuests: 7
        title: title
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        discountEnabled: true
        maxFemaleCount: 2
        duration: 2.027123
        offline: true
        genderRatioEnabled: true
        startDateTime: 2000-01-23T04:56:07.000+00:00
        hostUuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        maxAge: 5
        minAge: 1
        imageUrl: imageUrl
        minCapacity: 0
        place: place
        category: PARTY
        introduction: introduction
        status: OPEN
      properties:
        uuid:
          description: UUID of the gathering
          format: uuid
          type: string
        hostUuid:
          description: UUID of the host. tmp property
          format: uuid
          type: string
        approveType:
          $ref: "#/components/schemas/Gathering_ApproveType"
        minCapacity:
          description: Minimum capacity of the gathering
          type: integer
        maxCapacity:
          description: Maximum capacity of the gathering
          type: integer
        genderRatioEnabled:
          description: If host can set gender ratio for the gathering
          type: boolean
        minAge:
          description: Minimum age of guests
          type: integer
        maxAge:
          description: Maximum age of guests
          type: integer
        maxMaleCount:
          description: Maximum number of male guests
          type: integer
        maxFemaleCount:
          description: Maximum number of female guests
          type: integer
        totalGuests:
          description: Total number of guests
          type: integer
        fee:
          description: Fee to join the gathering
          type: integer
        discountEnabled:
          description: If host can set discount strategy for the gathering
          type: boolean
        offline:
          description: If the gathering is offline
          type: boolean
        place:
          description: Place where the gathering will be held
          type: string
        category:
          $ref: "#/components/schemas/Gathering_Category"
        subCategory:
          $ref: "#/components/schemas/Gathering_SubCategory"
        status:
          $ref: "#/components/schemas/Gathering_Status"
        imageUrl:
          description: URL of the gathering image
          type: string
        title:
          description: Title of the gathering
          type: string
        introduction:
          description: Introduction of the gathering
          type: string
        clickCount:
          description: Number of clicks on the gathering
          type: integer
        startDateTime:
          description: Start date and time of the gathering
          format: date-time
          type: string
        duration:
          description: Duration of the gathering in hours (can contain decimals)
          format: float
          type: number
      required:
      - approveType
      - category
      - clickCount
      - discountEnabled
      - fee
      - genderRatioEnabled
      - hostUuid
      - imageUrl
      - introduction
      - maxAge
      - maxCapacity
      - minAge
      - minCapacity
      - offline
      - place
      - startDateTime
      - status
      - subCategory
      - title
      - totalGuests
      - uuid
      type: object
    ScheduleSeriesRequest:
      discriminator:
        mapping:
          WEEKLY: "#/components/schemas/WeeklyScheduleSeriesRequest"
          DATE: "#/components/schemas/DateScheduleSeriesRequest"
        propertyName: scheduleType
      example:
        maxMaleCount: 1
        approveType: FIRST_IN
        subCategory: HOME_PARTY
        fee: 7
        maxCapacity: 6
        title: title
        discountEnabled: true
        maxFemaleCount: 5
        offline: true
        genderRatioEnabled: true
        scheduleType: WEEKLY
        hostUuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        maxAge: 2
        minAge: 5
        imageUrl: imageUrl
        minCapacity: 0
        place: place
        category: PARTY
        introduction: introduction
      properties:
        scheduleType:
          $ref: "#/components/schemas/Gathering_ScheduleType"
        hostUuid:
          description: UUID of the host. tmp property
          format: uuid
          type: string
        approveType:
          $ref: "#/components/schemas/Gathering_ApproveType"
        minCapacity:
          description: Minimum capacity of the gathering
          type: integer
        maxCapacity:
          description: Maximum capacity of the gathering
          type: integer
        maxMaleCount:
          description: Maximum number of male guests
          type: integer
        maxFemaleCount:
          description: Maximum number of female guests
          type: integer
        genderRatioEnabled:
          description: If host can set gender ratio for the gathering
          type: boolean
        minAge:
          description: Minimum age of guests
          type: integer
        maxAge:
          description: Maximum age of guests
          type: integer
        fee:
          description: Fee to join the gathering
          type: integer
        discountEnabled:
          description: If host can set discount strategy for the gathering
          type: boolean
        offline:
          description: If the gathering is offline
          type: boolean
        place:
          description: Place where the gathering will be held
          type: string
        category:
          $ref: "#/components/schemas/Gathering_Category"
        subCategory:
          $ref: "#/components/schemas/Gathering_SubCategory"
        imageUrl:
          description: URL of the gathering image
          type: string
        title:
          description: Title of the gathering
          type: string
        introduction:
          description: Introduction of the gathering
          type: string
      required:
      - approveType
      - category
      - discountEnabled
      - fee
      - genderRatioEnabled
      - hostUuid
      - imageUrl
      - introduction
      - maxAge
      - maxCapacity
      - minAge
      - minCapacity
      - offline
      - place
      - scheduleType
      - subCategory
      - title
      type: object
    WeeklyScheduleSeriesRequest:
      allOf:
      - $ref: "#/components/schemas/ScheduleSeriesRequest"
      - properties:
          startDate:
            description: Start date for this day of week schedule
            format: date
            type: string
          endDate:
            description: End date for this day of week schedule
            format: date
            type: string
          summaries:
            description: List of Schedule summaries for this day of week schedule
            items:
              $ref: "#/components/schemas/Gathering_WeeklyScheduleSummary"
            type: array
        required:
        - endDate
        - startDate
        - summaries
        type: object
    DateScheduleSeriesRequest:
      allOf:
      - $ref: "#/components/schemas/ScheduleSeriesRequest"
      - properties:
          summaries:
            description: List of Date Schedule summaries
            items:
              $ref: "#/components/schemas/Gathering_DateScheduleSummary"
            type: array
        required:
        - summaries
        type: object
    Gathering_ApproveType:
      description: Ways how to approve guests to join the gathering
      enum:
      - FIRST_IN
      - APPROVAL
      type: string
    Gathering_Category:
      description: Category of the gathering
      enum:
      - PARTY
      - FOOD_DRINK
      - STUDY
      - INVEST
      - LANGUAGE
      - ACTIVITY
      - CULTURE
      - LOVE
      type: string
    Gathering_SubCategory:
      description: Sub-category of the gathering
      enum:
      - HOME_PARTY
      type: string
    Gathering_Status:
      description: Status of the gathering
      enum:
      - OPEN
      - CLOSED
      - IN_PROGRESS
      - COMPLETED
      type: string
    Gathering_DayOfWeek:
      description: Day of the week
      enum:
      - SUNDAY
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SATURDAY
      type: string
    Gathering_WeeklyScheduleSummary:
      properties:
        dayOfWeek:
          $ref: "#/components/schemas/Gathering_DayOfWeek"
        startTime:
          description: Start time of the gathering on the specified day of week
          format: time
          type: string
        duration:
          description: Duration in hours (can contain decimals)
          format: float
          type: number
      required:
      - dayOfWeek
      - startTime
      type: object
    Gathering_DateScheduleSummary:
      properties:
        date:
          description: Date of the gathering
          format: date
          type: string
        startTime:
          description: Start time of the gathering on the specified date
          format: time
          type: string
        duration:
          description: Duration in hours (can contain decimals)
          format: float
          type: number
      required:
      - date
      - duration
      - startTime
      type: object
    Gathering_ScheduleType:
      description: Type of scheduling for the gatherings
      enum:
      - WEEKLY
      - DATE
      type: string
